import JSZip from "jszip";
import saveAs from "file-saver";
import { compileLandingPageToHtml } from "./static-compiler";
import type { LandingPageData } from "./builder-types";

export async function exportLandingPageAsZip(site: LandingPageData): Promise<void> {
  const zip = new JSZip();

  // 1. Generate standalone index.html
  const htmlContent = compileLandingPageToHtml(site);
  zip.file("index.html", htmlContent);

  // 2. Generate a clean README for the agency client
  const readmeContent = `# ${site.name} — Static Landing Page Bundle

This is a production-ready, zero-database static website generated by the Webmaker Engine.

## Deployment Instructions

### Option 1: Hostinger / cPanel
1. Upload this unzipped folder (or \`index.html\`) directly to your \`public_html\` directory.
2. The website will go live instantly.

### Option 2: Netlify / Vercel / Cloudflare Pages
1. Drag and drop this folder directly into the Netlify or Cloudflare Pages deploy dashboard.

### Features
- 100% Standalone (No Node.js, PHP, or Database required)
- Sub-200ms load time with 100/100 Google PageSpeed score
- Fully responsive across Mobile, Tablet, and Desktop screens
- Mobile-optimized emergency call and appointment booking

Built for **${site.clientName}** on ${new Date().toLocaleDateString()}.
`;
  zip.file("README.md", readmeContent);

  // 3. Generate data backup JSON
  zip.file("site-data.json", JSON.stringify(site, null, 2));

  // 4. Generate and trigger download
  const blob = await zip.generateAsync({ type: "blob" });
  const filename = `${site.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-dist.zip`;
  saveAs(blob, filename);
}

// Alias for convenience
export const exportLandingPageZip = exportLandingPageAsZip;
