import JSZip from "jszip";
import saveAs from "file-saver";
import { compileLandingPageToHtml } from "./static-compiler";
import { THEME_PALETTES, type LandingPageData } from "./builder-types";

export async function exportLandingPageAsZip(site: LandingPageData): Promise<void> {
  const zip = new JSZip();
  const theme = THEME_PALETTES[site.theme] || THEME_PALETTES.emerald;
  const domain = site.domain || `${site.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.health`;
  const todayIso = new Date().toISOString().split("T")[0];

  // 1. Generate 100% pure, sanitized standalone index.html (isEditable = false)
  const htmlContent = compileLandingPageToHtml(site, false);
  zip.file("index.html", htmlContent);

  // 2. Generate Google SEO XML Sitemap
  const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://${domain}/</loc>
    <lastmod>${todayIso}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>`;
  zip.file("sitemap.xml", sitemapContent);

  // 3. Generate Search Engine Crawler Directives (robots.txt)
  const robotsContent = `# Robots.txt for ${site.name}
User-agent: *
Allow: /

Sitemap: https://${domain}/sitemap.xml
`;
  zip.file("robots.txt", robotsContent);

  // 4. Generate Progressive Web App (PWA) Manifest
  const manifestContent = JSON.stringify(
    {
      name: site.name,
      short_name: site.name.slice(0, 15),
      start_url: "/",
      display: "standalone",
      background_color: "#ffffff",
      theme_color: theme.primary,
      description: site.seo?.description || `Official website for ${site.name}`,
    },
    null,
    2
  );
  zip.file("site.webmanifest", manifestContent);

  // 5. Generate Client Handover & Universal Deployment Guide
  const readmeContent = `# ${site.name} — Production Static Website Package

This package contains the complete, production-ready website generated by Webmaker.
It is 100% standalone and requires zero backend server runtimes, databases, or build steps.

---

## Deployment Options

### 1. Hostinger / cPanel / Standard Web Hosting
1. Log in to your hosting control panel (e.g. Hostinger hPanel or cPanel File Manager).
2. Navigate to your website's \`public_html/\` root folder.
3. Upload and extract this ZIP file (or upload \`index.html\`, \`sitemap.xml\`, \`robots.txt\`).
4. The website is live instantly with sub-100ms response times.

### 2. Netlify / Vercel / Cloudflare Pages
1. Go to your Netlify or Cloudflare Pages dashboard.
2. Drag and drop the unzipped folder into the deployment drop-zone.
3. Deploy is complete in 3 seconds.

### 3. Apache / Nginx / VPS
- **Nginx root directory**: \`/var/www/html\`
- **Apache document root**: \`/var/www/html\`

---

## Package Contents
- \`index.html\` — Pristine, semantic HTML5 with zero editor artifacts or tracking scripts.
- \`sitemap.xml\` — Search engine indexation sitemap.
- \`robots.txt\` — Web crawler configuration.
- \`site.webmanifest\` — Mobile app bookmarking and PWA configuration.
- \`site-data.json\` — Raw data backup for future re-import or edits.

---
Built for **${site.clientName}** on ${new Date().toLocaleDateString()}.
`;
  zip.file("README.md", readmeContent);

  // 6. Generate editable data backup JSON
  zip.file("site-data.json", JSON.stringify(site, null, 2));

  // 7. Compile ZIP and trigger browser download
  const blob = await zip.generateAsync({ type: "blob" });
  const filename = `${site.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-dist.zip`;
  saveAs(blob, filename);
}

// Alias for convenience
export const exportLandingPageZip = exportLandingPageAsZip;
